<?php
declare(strict_types=1);
/**
 * Writes the clean TF2 URLs (see scripts/tf2_url_helpers.php):
 *
 *   php scripts/build_tf2_urls.php          boot files + section pages + item pages
 *   php scripts/build_tf2_urls.php boot     only react/tf2-boot-*.js
 *   php scripts/build_tf2_urls.php pages    boot + /tf2/market|deals|mann-up|<category>/
 *   php scripts/build_tf2_urls.php items    boot + /tf2/<category>/<slug>/ (one per priced catalog row)
 *
 * Every clean page is a small, stable stub: its own title/description, the
 * base tag + guards, a route object, and <script src="react/tf2-boot-<page>.js">.
 * The boot file (served straight from /react/, 30 s cache) writes the page's
 * current stylesheets and theme block and loads its current scripts - it is
 * regenerated from the root page (tf2-item.html, tf2-market.html, ...) on
 * every run. So a new bundle or stylesheet tag reaches the ~73,000 item
 * pages by re-uploading four small boot files, never the pages themselves.
 * Item pages only need a rebuild + upload when the catalog gains items.
 */

require_once __DIR__ . '/tf2_url_helpers.php';

@ini_set('memory_limit', '2048M');
$root = dirname(__DIR__);
$mode = strtolower((string)($argv[1] ?? 'all'));
// Options for the tf2price.eu copy (scripts/build_tf2price_site.php):
//   --out=<dir>        write the boot files and pages under <dir> instead of
//                      this site (the source pages are still read from here)
//   --origin=<url>     the site address in canonical / og:url tags
$outRoot = $root;
$siteOrigin = 'https://csprice.eu';
foreach (array_slice($argv, 2) as $opt) {
    if (str_starts_with($opt, '--out=')) {
        $outRoot = rtrim(str_replace(chr(92), '/', substr($opt, 6)), '/');
    } elseif (str_starts_with($opt, '--origin=')) {
        $siteOrigin = rtrim(substr($opt, 9), '/');
    }
}

const TF2_BOOT_PAGES = [
    'item' => 'tf2-item.html',
    'market' => 'tf2-market.html',
    'deals' => 'tf2-deals.html',
    'drops' => 'tf2-drops.html',
];
const TF2_CATEGORY_LABELS = [
    'cosmetic' => 'Cosmetic', 'melee' => 'Melee Weapon', 'primary' => 'Primary Weapon', 'secondary' => 'Secondary Weapon',
    'tool' => 'Tool', 'crate' => 'Crate', 'package' => 'Package', 'craft_item' => 'Craft Item', 'gift' => 'Gift',
    'war_paint' => 'War Paint', 'taunt' => 'Taunt', 'strange_part' => 'Strange Part', 'party_favor' => 'Party Favor',
    'usable_item' => 'Usable Item', 'supply_crate' => 'Supply Crate', 'unusual' => 'Unusual',
];

function tf2Esc(string $s): string
{
    return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/** Writes $file only when its content changed; returns true when written. */
function tf2WriteIfChanged(string $file, string $content): bool
{
    if (!is_dir(dirname($file))) {
        @mkdir(dirname($file), 0755, true);
    }
    if (is_file($file) && (string)file_get_contents($file) === $content) {
        return false;
    }
    $dir = dirname($file);
    if (!is_dir($dir)) {
        mkdir($dir, 0775, true);
    }
    file_put_contents($file, $content);
    return true;
}

/** react/tf2-boot-<key>.js from the root page: its head payload and its scripts. */
function tf2BuildBoot(string $root, string $key, string $page, string $outRoot): bool
{
    $html = (string)file_get_contents($root . '/' . $page);
    $headEnd = stripos($html, '</head>');
    $first = stripos($html, '<link rel="stylesheet"');
    if ($headEnd === false || $first === false || $first > $headEnd) {
        throw new RuntimeException("$page: head payload not found");
    }
    $head = trim(substr($html, $first, $headEnd - $first));
    $body = substr($html, $headEnd);
    preg_match_all('#<script\b([^>]*)\bsrc="([^"]+)"([^>]*)></script>#i', $body, $m, PREG_SET_ORDER);
    $scripts = [];
    foreach ($m as $s) {
        $attrs = $s[1] . ' ' . $s[3];
        $cross = null;
        if (preg_match('/\bcrossorigin(?:="([^"]*)")?/i', $attrs, $c)) {
            $cross = $c[1] ?? '';
        }
        $scripts[] = ['src' => $s[2], 'crossorigin' => $cross];
    }
    if (!$scripts) {
        throw new RuntimeException("$page: no scripts found");
    }
    $js = "/* Generated by scripts/build_tf2_urls.php from $page - do not edit. */\n"
        . "(function () {\n"
        . "  // The page's stylesheets, theme block and head scripts, written in place\n"
        . "  // (parse-blocking CSS, no flash of unstyled content).\n"
        . "  document.write(" . json_encode($head, JSON_UNESCAPED_UNICODE) . ");\n"
        . "  // Its scripts, in order (async = false keeps the order for inserted scripts).\n"
        . "  var list = " . json_encode($scripts, JSON_UNESCAPED_SLASHES) . ";\n"
        . "  window.__tf2BootBody = function () {\n"
        . "    for (var i = 0; i < list.length; i++) {\n"
        . "      var el = document.createElement('script');\n"
        . "      el.src = list[i].src;\n"
        . "      if (list[i].crossorigin !== null) el.crossOrigin = list[i].crossorigin || 'anonymous';\n"
        . "      el.async = false;\n"
        . "      document.body.appendChild(el);\n"
        . "    }\n"
        . "  };\n"
        . "})();\n";
    return tf2WriteIfChanged($outRoot . "/react/tf2-boot-$key.js", $js);
}

/** The stub's fixed head: everything in the folder shell before its first stylesheet, SEO block replaced. */
function tf2StubPrefix(string $root): string
{
    static $prefix = null;
    if ($prefix !== null) {
        return $prefix;
    }
    // With --out, the output's own tf2-item/index.html (the tf2price.eu copy
    // carries its link guard) is the shell; otherwise this site's.
    global $outRoot;
    $shellFile = is_file($outRoot . '/tf2-item/index.html') ? $outRoot . '/tf2-item/index.html' : $root . '/tf2-item/index.html';
    $shell = (string)file_get_contents($shellFile);
    $first = stripos($shell, '<link rel="stylesheet"');
    if ($first === false) {
        throw new RuntimeException('tf2-item/index.html: no stylesheet found');
    }
    $prefix = substr($shell, 0, $first);
    $prefix = (string)preg_replace('#<title>.*?<!-- /seo -->#s', '{{SEO}}', $prefix, 1);
    if (!str_contains($prefix, '{{SEO}}') || !str_contains($prefix, '<base href=')) {
        throw new RuntimeException('tf2-item/index.html: SEO block or base tag missing');
    }
    return $prefix;
}

function tf2Stub(string $root, string $boot, string $path, string $title, string $desc, array $route): string
{
    global $siteOrigin;
    $url = $siteOrigin . '/' . $path;
    $seo = '<title>' . tf2Esc($title) . "</title>\n"
        . '<meta name="description" content="' . tf2Esc($desc) . "\">\n"
        . '<link rel="canonical" href="' . tf2Esc($url) . "\">\n"
        . "<meta property=\"og:type\" content=\"website\">\n"
        . "<meta property=\"og:site_name\" content=\"TFPRICE\">\n"
        . '<meta property="og:title" content="' . tf2Esc($title) . "\">\n"
        . '<meta property="og:description" content="' . tf2Esc($desc) . "\">\n"
        . '<meta property="og:url" content="' . tf2Esc($url) . "\">\n"
        . "<!-- /seo -->";
    $routeJs = json_encode($route, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
    return str_replace('{{SEO}}', $seo, tf2StubPrefix($root))
        . "  <script src=\"react/tf2-boot-$boot.js\"></script>\n"
        . "</head>\n<body>\n<div id=\"root\"></div>\n"
        . "<script>window.__TF2_ROUTE__=$routeJs;window.__tf2BootBody();</script>\n"
        . "</body>\n</html>\n";
}

// ---------------------------------------------------------------- boot
$bootWritten = 0;
foreach (TF2_BOOT_PAGES as $key => $page) {
    $bootWritten += tf2BuildBoot($root, $key, $page, $outRoot) ? 1 : 0;
}
echo "boot: $bootWritten of " . count(TF2_BOOT_PAGES) . " boot files changed\n";
if ($mode === 'boot') {
    exit(0);
}

// ---------------------------------------------------------------- section pages
if ($mode === 'all' || $mode === 'pages') {
    $written = 0;
    $pages = [
        ['market', 'tf2/market/', 'TF2 Market Explorer – Steam, Skinport, Mannco & DMarket Prices | TFPRICE', 'Every Team Fortress 2 item with Steam, Skinport, Mannco.store and DMarket prices side by side.', []],
        ['deals', 'tf2/deals/', 'TF2 Deals – Cheapest Prices Across Marketplaces | TFPRICE', 'Compare Team Fortress 2 item prices on Steam, Skinport, Mannco.store and DMarket and buy where it is cheapest.', []],
        ['drops', 'tf2/mann-up/', 'TF2 Mann Up Calculator – MvM Loot & Tour Rewards | TFPRICE', 'Simulate Mann vs. Machine Tours of Duty and see what the mission loot and tour rewards are worth on today\'s market.', []],
    ];
    foreach (TF2_CATEGORY_LABELS as $id => $label) {
        $seg = str_replace('_', '-', $id);
        $pages[] = ['market', "tf2/$seg/", "TF2 $label items – Steam, Skinport, Mannco & DMarket Prices | TFPRICE", "Every Team Fortress 2 $label item with Steam, Skinport, Mannco.store and DMarket prices.", ['cat' => $id]];
    }
    foreach ($pages as [$boot, $path, $title, $desc, $route]) {
        $written += tf2WriteIfChanged($outRoot . '/' . $path . 'index.html', tf2Stub($root, $boot, $path, $title, $desc, $route)) ? 1 : 0;
    }
    echo "pages: $written of " . count($pages) . " section pages changed\n";
}

// ---------------------------------------------------------------- item pages
if ($mode === 'all' || $mode === 'items') {
    $catalog = json_decode((string)file_get_contents($root . '/assets/data/tf2/catalog.json'), true);
    // One page per path; duplicate spellings of one item ("Force-a-Nature" /
    // "Force-A-Nature") share it, shown for the row with a Steam price and
    // the most listings.
    $byPath = [];
    foreach ($catalog['items'] as $r) {
        if (!tf2UrlPriced($r)) {
            continue;
        }
        $path = tf2ItemHref((string)$r['n'], (string)($r['e'] ?? ''), (string)($r['g'] ?? ''), (int)($r['b'] ?? -1));
        $cur = $byPath[$path] ?? null;
        $score = [isset($r['s']) ? 1 : 0, (int)($r['l'] ?? 0)];
        if ($cur === null || $score > $cur[1]) {
            $byPath[$path] = [$r, $score];
        }
    }
    $written = 0;
    foreach ($byPath as $path => [$r]) {
        $effect = (string)preg_replace('/^★\s*/u', '', (string)($r['e'] ?? ''));
        $name = ($effect !== '' ? $effect . ' ' : '') . $r['n'];
        $title = "$name – TF2 Price, Steam, Skinport, Mannco & DMarket | TFPRICE";
        $desc = "$name price on Steam, Skinport, Mannco.store and DMarket, with listings, price history and the cheapest place to buy.";
        $route = ['n' => (string)$r['n'], 'e' => (string)($r['e'] ?? ''), 'b' => (int)($r['b'] ?? -1)];
        $written += tf2WriteIfChanged($outRoot . '/' . $path . 'index.html', tf2Stub($root, 'item', $path, $title, $desc, $route)) ? 1 : 0;
    }
    echo "items: $written of " . count($byPath) . " item pages changed\n";
}
