<?php
/**
 * Clean URLs without server rewrites: for every top-level page (heavy.html,
 * deals.html, ...) this writes a folder copy at <name>/index.html, so
 * https://csprice.eu/heavy/ is served by nginx as a plain static file. The
 * copy gets a real <base href="<site path>"> at the top of <head>, so the
 * page's relative styles/scripts/links keep resolving from the site root
 * (the browser's preload scanner honours a static <base>; a scripted one
 * would cost a round of 404s first).
 *
 * The site path differs per environment: "/" on csprice.eu, "/csgo_price_tracker/"
 * on XAMPP. Pass it as the first argument; without one it is derived from
 * the folder name when the project sits under a htdocs directory, else "/".
 *
 *   C:\xampp\php\php.exe scripts\build_clean_urls.php            (local)
 *   C:\xampp\php\php.exe scripts\build_clean_urls.php /          (for the host; the deploy script does this)
 */
declare(strict_types=1);

$root = dirname(__DIR__);
$basePath = trim((string)($argv[1] ?? ''));
if ($basePath === '') {
    $basePath = preg_match('#[\\\\/]htdocs[\\\\/]#i', $root . DIRECTORY_SEPARATOR) ? '/' . basename($root) . '/' : '/';
}
if ($basePath[0] !== '/') {
    $basePath = '/' . $basePath;
}
if (!str_ends_with($basePath, '/')) {
    $basePath .= '/';
}

$skip = ['index.html', 'item_page.html'];

// The folder copies always ship the production base ("/") as a real tag, so
// the preload scanner resolves assets correctly on csprice.eu with no wasted
// requests. A tiny guard right after it swaps in the local path when the page
// is opened from XAMPP.
//
// This is deliberately independent of $basePath: running this script in either
// mode now produces the same file. Deploying used to flip the base to "/",
// sync, then flip it back, and two overlapping deploys left the local path on
// the server, which 404s every asset and blanks every clean URL.
$localBase = preg_match('#[\\\\/]htdocs[\\\\/]#i', $root . DIRECTORY_SEPARATOR)
    ? '/' . basename($root) . '/'
    : $basePath;
$baseTag = '<base href="/">'
    . "\n  " . '<script>/* csprice-base-guard */(function(){try{var h=location.hostname,'
    . 'local=(h==="localhost"||h==="127.0.0.1"||h==="[::1]"||h.indexOf("192.168.")===0),'
    . 'want=local?' . json_encode($localBase, JSON_UNESCAPED_SLASHES) . ':"/",'
    . 'b=document.getElementsByTagName("base")[0];'
    . 'if(b&&b.getAttribute("href")!==want){b.setAttribute("href",want);}}catch(e){}})();</script>';

$written = 0;
$unchanged = 0;
$count = 0;
foreach (glob($root . '/*.html') ?: [] as $file) {
    $name = basename($file);
    if (in_array($name, $skip, true) || preg_match('/^(tmp_|_tmp_)/i', $name)) {
        continue;
    }
    $slug = substr($name, 0, -5);
    $html = (string)file_get_contents($file);
    $hits = 0;
    $copy = preg_replace('/<head([^>]*)>/i', '<head$1>' . "\n  " . $baseTag, $html, 1, $hits);
    if ($hits !== 1 || !is_string($copy)) {
        fwrite(STDERR, "skip $name: no <head>\n");
        continue;
    }
    // The copy is what visitors and crawlers actually get, so point its
    // canonical/og:url at the clean path instead of the source .html page -
    // otherwise search engines index "csprice.eu/cases.html" and that ugly
    // URL is the one people see.
    $clean = 'https://csprice.eu/' . ($slug === 'index' ? '' : $slug . '/');
    foreach ([
        '#<link rel="canonical" href="[^"]*">#i' => '<link rel="canonical" href="' . $clean . '">',
        '#<meta property="og:url" content="[^"]*">#i' => '<meta property="og:url" content="' . $clean . '">',
        '#<meta name="twitter:url" content="[^"]*">#i' => '<meta name="twitter:url" content="' . $clean . '">',
    ] as $pattern => $replacement) {
        $copy = preg_replace($pattern, $replacement, $copy, 1) ?? $copy;
    }

    $copy = "<!-- generated by scripts/build_clean_urls.php from $name (base / on the host, $localBase locally) - edit the source page, not this copy -->\n" . $copy;
    $count++;
    $dir = $root . '/' . $slug;
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    $target = $dir . '/index.html';
    if (is_file($target) && file_get_contents($target) === $copy) {
        $unchanged++;
        continue;
    }
    file_put_contents($target, $copy);
    $written++;
}
printf("clean-url folders (base %s): %d written, %d unchanged, %d pages\n", $basePath, $written, $unchanged, $count);

// TF2's clean pages (tf2/market/, tf2/<category>/, tf2/<category>/<slug>/)
// are stubs that load react/tf2-boot-<page>.js, written from the root
// tf2-*.html pages. Refresh those boot files whenever the root pages were
// rebuilt or re-themed, so the stubs pick up the new stylesheet and script
// tags; upload the changed react/tf2-boot-*.js with the pages.
if (is_file($root . '/scripts/build_tf2_urls.php') && is_file($root . '/tf2-item.html')) {
    passthru(escapeshellarg(PHP_BINARY) . ' ' . escapeshellarg($root . '/scripts/build_tf2_urls.php') . ' boot');
}
